fake_joint_trajectory_controller:
  ros__parameters:
    joints:
      joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
      - mycobot_gripper_joint
    write_op_modes:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
      - mycobot_gripper_joint